name: pizza_repository
description: A new Flutter project

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Other dependencies...

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
